name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Build llama.cpp
      run: |
        cd llama.cpp
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DLLAMA_METAL=ON
        cmake --build build --config Release
    
    - name: Create deployment package
      run: |
        mkdir -p flama-release
        cp -r api scripts termux web *.md *.sh flama-release/
        cp -r llama.cpp/build/bin flama-release/llama-bin
        tar -czf flama-${{ github.ref_name }}.tar.gz flama-release/
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "flama-*.tar.gz"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          eduaigent/flama:latest
          eduaigent/flama:${{ github.ref_name }}